FROM rust:latest

RUN apt-get update && apt-get install -y protobuf-compiler 

WORKDIR /app

COPY ./ ./

RUN cargo build --release

ENV SERVER_ADDR="http://[::1]:50051" 

CMD ["sh", "-c", "/app/target/release/handin-2 -c ${SERVER_ADDR}"]
